apiVersion: v1
kind: Secret
metadata:
  name: kaleido-api
type: Opaque
stringData:
  DATABASE_URL: {{ required "databaseUrl is required" .Values.databaseUrl | quote }}
  DEPLOYER_PRIVATE_KEY: {{ required "deployerPrivateKey is required" .Values.deployerPrivateKey | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ required "keycloak.adminPassword is required" .Values.keycloak.adminPassword | quote }}
