// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contracts.sql

package db

import (
	"context"
)

const createContract = `-- name: CreateContract :one
INSERT INTO contracts (
    chain_id,
    address,
    deploy_tx_hash,
    base_uri,
    active
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, chain_id, address, deploy_tx_hash, base_uri, active, created_at, updated_at
`

type CreateContractParams struct {
	ChainID      int64
	Address      string
	DeployTxHash *string
	BaseUri      string
	Active       bool
}

func (q *Queries) CreateContract(ctx context.Context, arg CreateContractParams) (Contract, error) {
	row := q.db.QueryRow(ctx, createContract,
		arg.ChainID,
		arg.Address,
		arg.DeployTxHash,
		arg.BaseUri,
		arg.Active,
	)
	var i Contract
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.Address,
		&i.DeployTxHash,
		&i.BaseUri,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveContractByChainID = `-- name: GetActiveContractByChainID :one
SELECT id, chain_id, address, deploy_tx_hash, base_uri, active, created_at, updated_at
FROM contracts
WHERE chain_id = $1
  AND active = true
`

func (q *Queries) GetActiveContractByChainID(ctx context.Context, chainID int64) (Contract, error) {
	row := q.db.QueryRow(ctx, getActiveContractByChainID, chainID)
	var i Contract
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.Address,
		&i.DeployTxHash,
		&i.BaseUri,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContractByID = `-- name: GetContractByID :one
SELECT id, chain_id, address, deploy_tx_hash, base_uri, active, created_at, updated_at
FROM contracts
WHERE id = $1
`

func (q *Queries) GetContractByID(ctx context.Context, id int64) (Contract, error) {
	row := q.db.QueryRow(ctx, getContractByID, id)
	var i Contract
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.Address,
		&i.DeployTxHash,
		&i.BaseUri,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
