// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: identities.sql

package db

import (
	"context"
)

const createSigningKey = `-- name: CreateSigningKey :one
INSERT INTO signing_keys (
    identity_id,
    address,
    ciphertext,
    encryptor,
    key_version
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, identity_id, address, ciphertext, encryptor, key_version, created_at
`

type CreateSigningKeyParams struct {
	IdentityID int64
	Address    string
	Ciphertext []byte
	Encryptor  string
	KeyVersion int32
}

func (q *Queries) CreateSigningKey(ctx context.Context, arg CreateSigningKeyParams) (SigningKey, error) {
	row := q.db.QueryRow(ctx, createSigningKey,
		arg.IdentityID,
		arg.Address,
		arg.Ciphertext,
		arg.Encryptor,
		arg.KeyVersion,
	)
	var i SigningKey
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Address,
		&i.Ciphertext,
		&i.Encryptor,
		&i.KeyVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getIdentityByID = `-- name: GetIdentityByID :one
SELECT id, issuer, subject, role, created_at
FROM identities
WHERE id = $1
`

func (q *Queries) GetIdentityByID(ctx context.Context, id int64) (Identity, error) {
	row := q.db.QueryRow(ctx, getIdentityByID, id)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.Issuer,
		&i.Subject,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getIdentityByIssuerSubject = `-- name: GetIdentityByIssuerSubject :one
SELECT id, issuer, subject, role, created_at
FROM identities
WHERE issuer = $1
  AND subject = $2
`

type GetIdentityByIssuerSubjectParams struct {
	Issuer  string
	Subject string
}

func (q *Queries) GetIdentityByIssuerSubject(ctx context.Context, arg GetIdentityByIssuerSubjectParams) (Identity, error) {
	row := q.db.QueryRow(ctx, getIdentityByIssuerSubject, arg.Issuer, arg.Subject)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.Issuer,
		&i.Subject,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getOrCreateIdentity = `-- name: GetOrCreateIdentity :one
INSERT INTO identities (
    issuer,
    subject,
    role
) VALUES (
    $1, $2, $3
)
ON CONFLICT (issuer, subject) DO UPDATE SET role = identities.role
RETURNING id, issuer, subject, role, created_at
`

type GetOrCreateIdentityParams struct {
	Issuer  string
	Subject string
	Role    string
}

func (q *Queries) GetOrCreateIdentity(ctx context.Context, arg GetOrCreateIdentityParams) (Identity, error) {
	row := q.db.QueryRow(ctx, getOrCreateIdentity, arg.Issuer, arg.Subject, arg.Role)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.Issuer,
		&i.Subject,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getSigningKeyByAddress = `-- name: GetSigningKeyByAddress :one
SELECT id, identity_id, address, ciphertext, encryptor, key_version, created_at
FROM signing_keys
WHERE lower(address) = lower($1)
`

func (q *Queries) GetSigningKeyByAddress(ctx context.Context, lower string) (SigningKey, error) {
	row := q.db.QueryRow(ctx, getSigningKeyByAddress, lower)
	var i SigningKey
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Address,
		&i.Ciphertext,
		&i.Encryptor,
		&i.KeyVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getSigningKeyByIdentityID = `-- name: GetSigningKeyByIdentityID :one
SELECT id, identity_id, address, ciphertext, encryptor, key_version, created_at
FROM signing_keys
WHERE identity_id = $1
`

func (q *Queries) GetSigningKeyByIdentityID(ctx context.Context, identityID int64) (SigningKey, error) {
	row := q.db.QueryRow(ctx, getSigningKeyByIdentityID, identityID)
	var i SigningKey
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Address,
		&i.Ciphertext,
		&i.Encryptor,
		&i.KeyVersion,
		&i.CreatedAt,
	)
	return i, err
}
