// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: loans.sql

package db

import (
	"context"
)

const createLoan = `-- name: CreateLoan :one
INSERT INTO loans (
    borrower_ref,
    lender_address,
    lender_identity_id,
    principal_minor,
    apr_bps,
    term_days,
    interest_due_minor,
    total_due_minor,
    outstanding_minor,
    status,
    mint_operation_id,
    contract_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, token_id, contract_id, borrower_ref, lender_address, principal_minor, apr_bps, term_days, interest_due_minor, total_due_minor, outstanding_minor, status, mint_operation_id, created_at, updated_at, lender_identity_id
`

type CreateLoanParams struct {
	BorrowerRef      string
	LenderAddress    string
	LenderIdentityID *int64
	PrincipalMinor   int64
	AprBps           int32
	TermDays         int64
	InterestDueMinor int64
	TotalDueMinor    int64
	OutstandingMinor int64
	Status           string
	MintOperationID  *int64
	ContractID       *int64
}

func (q *Queries) CreateLoan(ctx context.Context, arg CreateLoanParams) (Loan, error) {
	row := q.db.QueryRow(ctx, createLoan,
		arg.BorrowerRef,
		arg.LenderAddress,
		arg.LenderIdentityID,
		arg.PrincipalMinor,
		arg.AprBps,
		arg.TermDays,
		arg.InterestDueMinor,
		arg.TotalDueMinor,
		arg.OutstandingMinor,
		arg.Status,
		arg.MintOperationID,
		arg.ContractID,
	)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.ContractID,
		&i.BorrowerRef,
		&i.LenderAddress,
		&i.PrincipalMinor,
		&i.AprBps,
		&i.TermDays,
		&i.InterestDueMinor,
		&i.TotalDueMinor,
		&i.OutstandingMinor,
		&i.Status,
		&i.MintOperationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LenderIdentityID,
	)
	return i, err
}

const getLoanByID = `-- name: GetLoanByID :one
SELECT id, token_id, contract_id, borrower_ref, lender_address, principal_minor, apr_bps, term_days, interest_due_minor, total_due_minor, outstanding_minor, status, mint_operation_id, created_at, updated_at, lender_identity_id
FROM loans
WHERE id = $1
`

func (q *Queries) GetLoanByID(ctx context.Context, id int64) (Loan, error) {
	row := q.db.QueryRow(ctx, getLoanByID, id)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.ContractID,
		&i.BorrowerRef,
		&i.LenderAddress,
		&i.PrincipalMinor,
		&i.AprBps,
		&i.TermDays,
		&i.InterestDueMinor,
		&i.TotalDueMinor,
		&i.OutstandingMinor,
		&i.Status,
		&i.MintOperationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LenderIdentityID,
	)
	return i, err
}

const getLoanByIDForUpdate = `-- name: GetLoanByIDForUpdate :one
SELECT id, token_id, contract_id, borrower_ref, lender_address, principal_minor, apr_bps, term_days, interest_due_minor, total_due_minor, outstanding_minor, status, mint_operation_id, created_at, updated_at, lender_identity_id
FROM loans
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetLoanByIDForUpdate(ctx context.Context, id int64) (Loan, error) {
	row := q.db.QueryRow(ctx, getLoanByIDForUpdate, id)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.ContractID,
		&i.BorrowerRef,
		&i.LenderAddress,
		&i.PrincipalMinor,
		&i.AprBps,
		&i.TermDays,
		&i.InterestDueMinor,
		&i.TotalDueMinor,
		&i.OutstandingMinor,
		&i.Status,
		&i.MintOperationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LenderIdentityID,
	)
	return i, err
}

const listLoans = `-- name: ListLoans :many
SELECT id, token_id, contract_id, borrower_ref, lender_address, principal_minor, apr_bps, term_days, interest_due_minor, total_due_minor, outstanding_minor, status, mint_operation_id, created_at, updated_at, lender_identity_id
FROM loans
WHERE ($1::text = '' OR lower(lender_address) = lower($1::text))
  AND ($2::bigint = 0 OR lender_identity_id = $2::bigint)
  AND ($3::text = '' OR status = $3::text)
ORDER BY id DESC
LIMIT $5
OFFSET $4
`

type ListLoansParams struct {
	Lender           string
	LenderIdentityID int64
	Status           string
	OffsetCount      int32
	LimitCount       int32
}

func (q *Queries) ListLoans(ctx context.Context, arg ListLoansParams) ([]Loan, error) {
	rows, err := q.db.Query(ctx, listLoans,
		arg.Lender,
		arg.LenderIdentityID,
		arg.Status,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Loan
	for rows.Next() {
		var i Loan
		if err := rows.Scan(
			&i.ID,
			&i.TokenID,
			&i.ContractID,
			&i.BorrowerRef,
			&i.LenderAddress,
			&i.PrincipalMinor,
			&i.AprBps,
			&i.TermDays,
			&i.InterestDueMinor,
			&i.TotalDueMinor,
			&i.OutstandingMinor,
			&i.Status,
			&i.MintOperationID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LenderIdentityID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLoanActive = `-- name: SetLoanActive :one
UPDATE loans
SET token_id = $2,
    status = 'active',
    mint_operation_id = $3,
    contract_id = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, token_id, contract_id, borrower_ref, lender_address, principal_minor, apr_bps, term_days, interest_due_minor, total_due_minor, outstanding_minor, status, mint_operation_id, created_at, updated_at, lender_identity_id
`

type SetLoanActiveParams struct {
	ID              int64
	TokenID         *string
	MintOperationID *int64
	ContractID      *int64
}

func (q *Queries) SetLoanActive(ctx context.Context, arg SetLoanActiveParams) (Loan, error) {
	row := q.db.QueryRow(ctx, setLoanActive,
		arg.ID,
		arg.TokenID,
		arg.MintOperationID,
		arg.ContractID,
	)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.ContractID,
		&i.BorrowerRef,
		&i.LenderAddress,
		&i.PrincipalMinor,
		&i.AprBps,
		&i.TermDays,
		&i.InterestDueMinor,
		&i.TotalDueMinor,
		&i.OutstandingMinor,
		&i.Status,
		&i.MintOperationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LenderIdentityID,
	)
	return i, err
}

const setLoanStatus = `-- name: SetLoanStatus :one
UPDATE loans
SET status = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, token_id, contract_id, borrower_ref, lender_address, principal_minor, apr_bps, term_days, interest_due_minor, total_due_minor, outstanding_minor, status, mint_operation_id, created_at, updated_at, lender_identity_id
`

type SetLoanStatusParams struct {
	ID     int64
	Status string
}

func (q *Queries) SetLoanStatus(ctx context.Context, arg SetLoanStatusParams) (Loan, error) {
	row := q.db.QueryRow(ctx, setLoanStatus, arg.ID, arg.Status)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.ContractID,
		&i.BorrowerRef,
		&i.LenderAddress,
		&i.PrincipalMinor,
		&i.AprBps,
		&i.TermDays,
		&i.InterestDueMinor,
		&i.TotalDueMinor,
		&i.OutstandingMinor,
		&i.Status,
		&i.MintOperationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LenderIdentityID,
	)
	return i, err
}

const updateLoanLender = `-- name: UpdateLoanLender :one
UPDATE loans
SET lender_address = $2,
    lender_identity_id = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, token_id, contract_id, borrower_ref, lender_address, principal_minor, apr_bps, term_days, interest_due_minor, total_due_minor, outstanding_minor, status, mint_operation_id, created_at, updated_at, lender_identity_id
`

type UpdateLoanLenderParams struct {
	ID               int64
	LenderAddress    string
	LenderIdentityID *int64
}

func (q *Queries) UpdateLoanLender(ctx context.Context, arg UpdateLoanLenderParams) (Loan, error) {
	row := q.db.QueryRow(ctx, updateLoanLender, arg.ID, arg.LenderAddress, arg.LenderIdentityID)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.ContractID,
		&i.BorrowerRef,
		&i.LenderAddress,
		&i.PrincipalMinor,
		&i.AprBps,
		&i.TermDays,
		&i.InterestDueMinor,
		&i.TotalDueMinor,
		&i.OutstandingMinor,
		&i.Status,
		&i.MintOperationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LenderIdentityID,
	)
	return i, err
}

const updateLoanOutstandingAndStatus = `-- name: UpdateLoanOutstandingAndStatus :one
UPDATE loans
SET outstanding_minor = $2,
    status = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, token_id, contract_id, borrower_ref, lender_address, principal_minor, apr_bps, term_days, interest_due_minor, total_due_minor, outstanding_minor, status, mint_operation_id, created_at, updated_at, lender_identity_id
`

type UpdateLoanOutstandingAndStatusParams struct {
	ID               int64
	OutstandingMinor int64
	Status           string
}

func (q *Queries) UpdateLoanOutstandingAndStatus(ctx context.Context, arg UpdateLoanOutstandingAndStatusParams) (Loan, error) {
	row := q.db.QueryRow(ctx, updateLoanOutstandingAndStatus, arg.ID, arg.OutstandingMinor, arg.Status)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.ContractID,
		&i.BorrowerRef,
		&i.LenderAddress,
		&i.PrincipalMinor,
		&i.AprBps,
		&i.TermDays,
		&i.InterestDueMinor,
		&i.TotalDueMinor,
		&i.OutstandingMinor,
		&i.Status,
		&i.MintOperationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LenderIdentityID,
	)
	return i, err
}
