// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: locks.sql

package db

import (
	"context"
	"time"
)

const acquireAppLock = `-- name: AcquireAppLock :one
INSERT INTO app_locks (
    name,
    holder,
    expires_at
) VALUES (
    $1, $2, $3
)
ON CONFLICT (name) DO UPDATE
SET holder = EXCLUDED.holder,
    expires_at = EXCLUDED.expires_at,
    updated_at = now()
WHERE app_locks.expires_at < now()
   OR app_locks.holder = EXCLUDED.holder
RETURNING name, holder, expires_at, created_at, updated_at
`

type AcquireAppLockParams struct {
	Name      string
	Holder    string
	ExpiresAt time.Time
}

func (q *Queries) AcquireAppLock(ctx context.Context, arg AcquireAppLockParams) (AppLock, error) {
	row := q.db.QueryRow(ctx, acquireAppLock, arg.Name, arg.Holder, arg.ExpiresAt)
	var i AppLock
	err := row.Scan(
		&i.Name,
		&i.Holder,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const releaseAppLock = `-- name: ReleaseAppLock :exec
DELETE FROM app_locks
WHERE name = $1
  AND holder = $2
`

type ReleaseAppLockParams struct {
	Name   string
	Holder string
}

func (q *Queries) ReleaseAppLock(ctx context.Context, arg ReleaseAppLockParams) error {
	_, err := q.db.Exec(ctx, releaseAppLock, arg.Name, arg.Holder)
	return err
}
