// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type AppLock struct {
	Name      string
	Holder    string
	ExpiresAt time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ChainOperation struct {
	ID         int64
	Kind       string
	Status     string
	ContractID *int64
	LoanID     *int64
	TxHash     *string
	Nonce      *int64
	Error      *string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Contract struct {
	ID           int64
	ChainID      int64
	Address      string
	DeployTxHash *string
	BaseUri      string
	Active       bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Identity struct {
	ID        int64
	Issuer    string
	Subject   string
	Role      string
	CreatedAt time.Time
}

type Loan struct {
	ID               int64
	TokenID          *string
	ContractID       *int64
	BorrowerRef      string
	LenderAddress    string
	PrincipalMinor   int64
	AprBps           int32
	TermDays         int64
	InterestDueMinor int64
	TotalDueMinor    int64
	OutstandingMinor int64
	Status           string
	MintOperationID  *int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
	LenderIdentityID *int64
}

type Repayment struct {
	ID          int64
	LoanID      int64
	AmountMinor int64
	ExternalRef *string
	CreatedAt   time.Time
}

type SigningKey struct {
	ID         int64
	IdentityID int64
	Address    string
	Ciphertext []byte
	Encryptor  string
	KeyVersion int32
	CreatedAt  time.Time
}
