// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: operations.sql

package db

import (
	"context"
)

const attachOperationContract = `-- name: AttachOperationContract :one
UPDATE chain_operations
SET contract_id = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, kind, status, contract_id, loan_id, tx_hash, nonce, error, created_at, updated_at, signer_address
`

type AttachOperationContractParams struct {
	ID         int64
	ContractID *int64
}

func (q *Queries) AttachOperationContract(ctx context.Context, arg AttachOperationContractParams) (ChainOperation, error) {
	row := q.db.QueryRow(ctx, attachOperationContract, arg.ID, arg.ContractID)
	var i ChainOperation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.ContractID,
		&i.LoanID,
		&i.TxHash,
		&i.Nonce,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SignerAddress,
	)
	return i, err
}

const createChainOperation = `-- name: CreateChainOperation :one
INSERT INTO chain_operations (
    kind,
    status,
    contract_id,
    loan_id
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, kind, status, contract_id, loan_id, tx_hash, nonce, error, created_at, updated_at, signer_address
`

type CreateChainOperationParams struct {
	Kind       string
	Status     string
	ContractID *int64
	LoanID     *int64
}

func (q *Queries) CreateChainOperation(ctx context.Context, arg CreateChainOperationParams) (ChainOperation, error) {
	row := q.db.QueryRow(ctx, createChainOperation,
		arg.Kind,
		arg.Status,
		arg.ContractID,
		arg.LoanID,
	)
	var i ChainOperation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.ContractID,
		&i.LoanID,
		&i.TxHash,
		&i.Nonce,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SignerAddress,
	)
	return i, err
}

const getChainOperationByID = `-- name: GetChainOperationByID :one
SELECT id, kind, status, contract_id, loan_id, tx_hash, nonce, error, created_at, updated_at, signer_address
FROM chain_operations
WHERE id = $1
`

func (q *Queries) GetChainOperationByID(ctx context.Context, id int64) (ChainOperation, error) {
	row := q.db.QueryRow(ctx, getChainOperationByID, id)
	var i ChainOperation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.ContractID,
		&i.LoanID,
		&i.TxHash,
		&i.Nonce,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SignerAddress,
	)
	return i, err
}

const setOperationApplied = `-- name: SetOperationApplied :one
UPDATE chain_operations
SET status = 'applied',
    error = NULL,
    updated_at = now()
WHERE id = $1
RETURNING id, kind, status, contract_id, loan_id, tx_hash, nonce, error, created_at, updated_at, signer_address
`

func (q *Queries) SetOperationApplied(ctx context.Context, id int64) (ChainOperation, error) {
	row := q.db.QueryRow(ctx, setOperationApplied, id)
	var i ChainOperation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.ContractID,
		&i.LoanID,
		&i.TxHash,
		&i.Nonce,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SignerAddress,
	)
	return i, err
}

const setOperationMined = `-- name: SetOperationMined :one
UPDATE chain_operations
SET status = 'mined',
    error = NULL,
    updated_at = now()
WHERE id = $1
RETURNING id, kind, status, contract_id, loan_id, tx_hash, nonce, error, created_at, updated_at, signer_address
`

func (q *Queries) SetOperationMined(ctx context.Context, id int64) (ChainOperation, error) {
	row := q.db.QueryRow(ctx, setOperationMined, id)
	var i ChainOperation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.ContractID,
		&i.LoanID,
		&i.TxHash,
		&i.Nonce,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SignerAddress,
	)
	return i, err
}

const setOperationRetryable = `-- name: SetOperationRetryable :one
UPDATE chain_operations
SET status = 'retryable',
    error = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, kind, status, contract_id, loan_id, tx_hash, nonce, error, created_at, updated_at, signer_address
`

type SetOperationRetryableParams struct {
	ID    int64
	Error *string
}

func (q *Queries) SetOperationRetryable(ctx context.Context, arg SetOperationRetryableParams) (ChainOperation, error) {
	row := q.db.QueryRow(ctx, setOperationRetryable, arg.ID, arg.Error)
	var i ChainOperation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.ContractID,
		&i.LoanID,
		&i.TxHash,
		&i.Nonce,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SignerAddress,
	)
	return i, err
}

const setOperationSubmitted = `-- name: SetOperationSubmitted :one
UPDATE chain_operations
SET status = 'submitted',
    tx_hash = $2,
    nonce = $3,
    signer_address = $4,
    error = NULL,
    updated_at = now()
WHERE id = $1
RETURNING id, kind, status, contract_id, loan_id, tx_hash, nonce, error, created_at, updated_at, signer_address
`

type SetOperationSubmittedParams struct {
	ID            int64
	TxHash        *string
	Nonce         *int64
	SignerAddress *string
}

func (q *Queries) SetOperationSubmitted(ctx context.Context, arg SetOperationSubmittedParams) (ChainOperation, error) {
	row := q.db.QueryRow(ctx, setOperationSubmitted,
		arg.ID,
		arg.TxHash,
		arg.Nonce,
		arg.SignerAddress,
	)
	var i ChainOperation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.ContractID,
		&i.LoanID,
		&i.TxHash,
		&i.Nonce,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SignerAddress,
	)
	return i, err
}
