// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repayments.sql

package db

import (
	"context"
)

const createRepayment = `-- name: CreateRepayment :one
INSERT INTO repayments (
    loan_id,
    amount_minor,
    external_ref
) VALUES (
    $1, $2, $3
)
RETURNING id, loan_id, amount_minor, external_ref, created_at
`

type CreateRepaymentParams struct {
	LoanID      int64
	AmountMinor int64
	ExternalRef *string
}

func (q *Queries) CreateRepayment(ctx context.Context, arg CreateRepaymentParams) (Repayment, error) {
	row := q.db.QueryRow(ctx, createRepayment, arg.LoanID, arg.AmountMinor, arg.ExternalRef)
	var i Repayment
	err := row.Scan(
		&i.ID,
		&i.LoanID,
		&i.AmountMinor,
		&i.ExternalRef,
		&i.CreatedAt,
	)
	return i, err
}

const listRepaymentsByLoan = `-- name: ListRepaymentsByLoan :many
SELECT id, loan_id, amount_minor, external_ref, created_at
FROM repayments
WHERE loan_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListRepaymentsByLoan(ctx context.Context, loanID int64) ([]Repayment, error) {
	rows, err := q.db.Query(ctx, listRepaymentsByLoan, loanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repayment
	for rows.Next() {
		var i Repayment
		if err := rows.Scan(
			&i.ID,
			&i.LoanID,
			&i.AmountMinor,
			&i.ExternalRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
