// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Service metadata",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.serviceInfoResponse"
                        }
                    }
                }
            }
        },
        "/admin/contracts/deploy": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deploys a new LoanNote contract instance; each instance is its own loan series. The chain's first contract becomes the origination default; later deploys only take over the default when activate is true.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contracts"
                ],
                "summary": "Deploy a LoanNote contract",
                "parameters": [
                    {
                        "description": "Optional base URI override and activation flag. Empty body uses the configured default base URI",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/api.deployContractRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.contractResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON body",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "503": {
                        "description": "Another chain operation is in progress, retry shortly",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/admin/contracts/{id}/activate": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Makes the contract the default for new originations, replacing the current default.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contracts"
                ],
                "summary": "Activate contract",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Contract ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.contractResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/contracts": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contracts"
                ],
                "summary": "List contracts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.contractsListResponse"
                        }
                    }
                }
            }
        },
        "/contracts/active": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contracts"
                ],
                "summary": "Active contract",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.contractResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/contracts/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contracts"
                ],
                "summary": "Get contract",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Contract ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.contractResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Liveness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.healthResponse"
                        }
                    }
                }
            }
        },
        "/lenders/onboard": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates the caller's lender identity and eagerly provisions their custodial wallet. Idempotent: an already-onboarded lender gets their existing identity back. A lender must onboard before they can be named as lender_subject or to_subject.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lenders"
                ],
                "summary": "Onboard as a lender",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.onboardResponse"
                        }
                    },
                    "403": {
                        "description": "Platform service accounts do not onboard as lenders",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/loans": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "loans"
                ],
                "summary": "List loans",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by lender address (case-insensitive)",
                        "name": "lender",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "originating",
                            "active",
                            "settling",
                            "repaid",
                            "defaulted"
                        ],
                        "type": "string",
                        "description": "Filter by loan status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 50,
                        "description": "Page size",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "description": "Result offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.loansListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "loans"
                ],
                "summary": "Originate a loan note",
                "parameters": [
                    {
                        "description": "Loan to originate",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.createLoanRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.loanResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "409": {
                        "description": "No active contract deployed",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "503": {
                        "description": "Another chain operation is in progress, retry shortly",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/loans/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "loans"
                ],
                "summary": "Get loan",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Loan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.loanResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/loans/{id}/default": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "loans"
                ],
                "summary": "Mark loan defaulted",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Loan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.loanResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Loan is not active",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "503": {
                        "description": "Another chain operation is in progress, retry shortly",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/loans/{id}/repayments": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "loans"
                ],
                "summary": "List repayments",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Loan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.repaymentsListResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "loans"
                ],
                "summary": "Record repayment",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Loan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Repayment to record",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.createRepaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.repaymentResultResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid amount or overpayment",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Loan not active or duplicate external_ref",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "503": {
                        "description": "Another chain operation is in progress, retry shortly",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/loans/{id}/terms": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "loans"
                ],
                "summary": "Loan terms for tokenURI",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Loan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.termsResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/loans/{id}/transfer": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "loans"
                ],
                "summary": "Transfer loan note",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Loan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Transfer target",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.transferLoanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.loanResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "403": {
                        "description": "Caller does not own the note",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Loan is not transferable",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "503": {
                        "description": "Another chain operation is in progress, retry shortly",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/ready": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Readiness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.readinessResponse"
                        }
                    },
                    "503": {
                        "description": "One or more readiness checks failed",
                        "schema": {
                            "$ref": "#/definitions/api.readinessResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.contractResponse": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "address": {
                    "type": "string"
                },
                "base_uri": {
                    "type": "string"
                },
                "chain_id": {
                    "type": "integer"
                },
                "deploy_tx_hash": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "api.contractsListResponse": {
            "type": "object",
            "properties": {
                "contracts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.contractResponse"
                    }
                }
            }
        },
        "api.createLoanRequest": {
            "type": "object",
            "properties": {
                "apr_bps": {
                    "type": "integer"
                },
                "borrower_ref": {
                    "type": "string"
                },
                "contract_id": {
                    "description": "ContractID selects the loan series to originate into; omit it to use the chain's active contract.",
                    "type": "integer"
                },
                "lender_address": {
                    "description": "Exactly one of lender_address (external wallet) and lender_subject (custodial identity) is required.",
                    "type": "string"
                },
                "lender_subject": {
                    "type": "string"
                },
                "principal_minor": {
                    "type": "integer"
                },
                "term_days": {
                    "type": "integer"
                }
            }
        },
        "api.createRepaymentRequest": {
            "type": "object",
            "properties": {
                "amount_minor": {
                    "type": "integer"
                },
                "external_ref": {
                    "type": "string"
                }
            }
        },
        "api.deployContractRequest": {
            "type": "object",
            "properties": {
                "activate": {
                    "description": "Activate makes the new contract the default for new originations, replacing the current default.\nThe chain's first contract always becomes the default regardless of this flag.",
                    "type": "boolean"
                },
                "base_uri": {
                    "type": "string"
                }
            }
        },
        "api.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "api.healthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "api.loanResponse": {
            "type": "object",
            "properties": {
                "apr_bps": {
                    "type": "integer"
                },
                "borrower_ref": {
                    "type": "string"
                },
                "contract_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "interest_due_minor": {
                    "type": "integer"
                },
                "lender_address": {
                    "type": "string"
                },
                "lender_subject": {
                    "type": "string"
                },
                "operation_id": {
                    "type": "integer"
                },
                "outstanding_minor": {
                    "type": "integer"
                },
                "owner_address": {
                    "type": "string"
                },
                "principal_minor": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "term_days": {
                    "type": "integer"
                },
                "token_id": {
                    "type": "string"
                },
                "total_due_minor": {
                    "type": "integer"
                },
                "tx_hash": {
                    "type": "string"
                }
            }
        },
        "api.loansListResponse": {
            "type": "object",
            "properties": {
                "loans": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.loanResponse"
                    }
                }
            }
        },
        "api.onboardResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "0x1C7021cc3fAa237D4B837268dc19c12B6003D449"
                },
                "issuer": {
                    "type": "string"
                },
                "subject": {
                    "type": "string",
                    "example": "080dfd67-ccc1-49c1-8a30-c292b3a4a7cf"
                }
            }
        },
        "api.readinessResponse": {
            "type": "object",
            "properties": {
                "active_contract": {
                    "type": "string"
                },
                "checks": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "started_at": {
                    "type": "string",
                    "example": "2026-01-02T15:04:05Z"
                },
                "status": {
                    "type": "string",
                    "example": "ready"
                }
            }
        },
        "api.repaymentResponse": {
            "type": "object",
            "properties": {
                "amount_minor": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "external_ref": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "loan_id": {
                    "type": "integer"
                }
            }
        },
        "api.repaymentResultResponse": {
            "type": "object",
            "properties": {
                "loan": {
                    "$ref": "#/definitions/api.loanResponse"
                },
                "repayment": {
                    "$ref": "#/definitions/api.repaymentResponse"
                },
                "settlement_operation_id": {
                    "type": "integer"
                },
                "settlement_tx_hash": {
                    "type": "string"
                }
            }
        },
        "api.repaymentsListResponse": {
            "type": "object",
            "properties": {
                "repayments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.repaymentResponse"
                    }
                }
            }
        },
        "api.serviceInfoResponse": {
            "type": "object",
            "properties": {
                "service": {
                    "type": "string"
                },
                "signer_address": {
                    "type": "string",
                    "example": "0x627306090abaB3A6e1400e9345bC60c78a8BEf57"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "api.termsResponse": {
            "type": "object",
            "properties": {
                "apr_bps": {
                    "type": "integer"
                },
                "interest_due_minor": {
                    "type": "integer"
                },
                "principal_minor": {
                    "type": "integer"
                },
                "term_days": {
                    "type": "integer"
                },
                "total_due_minor": {
                    "type": "integer"
                }
            }
        },
        "api.transferLoanRequest": {
            "type": "object",
            "properties": {
                "to_address": {
                    "description": "Exactly one of to_address (external wallet) and to_subject (custodial identity) is required.",
                    "type": "string"
                },
                "to_subject": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "OIDC bearer token, sent as \"Bearer \u003ctoken\u003e\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Loan Note API",
	Description:      "API for managing ERC-721-backed loan notes",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
